steps:
  - label: ":docker: build docker image"
    command:
      - "sudo rm -rf /var/lib/buildkite-agent/builds/ci-test-runner*/cyberway/uniswapv2-core"
      - ".buildkite/steps/build-image.sh"
      - ".buildkite/steps/upload-image.sh"

  - wait

  - label: ":cop::skin-tone-2: deploy check"
    command: ".buildkite/steps/deploy-test.sh"
    timeout: 120
    agents:
      queue: "testing"

  - wait

  - label: ":floppy_disk: publish image"
    command: ".buildkite/steps/publish-image.sh"
    branches: "master develop ci-* v*.*.*"
